'''
Author     :  AnurajPilanku
Use Case   :IPI2K Data Batch Verification
Code Utility : Copy exe executed xlsx file to CAC Network Path
'''

import os
import datetime
import sys
import glob
import shutil


#file_path=sys.argv[1]
#destination_dir=sys.argv[2]
file_path=r"\\pmcsnttest64\DropBox\Cognizant\MEP_Verifier"
destination_dir=r"\\acprd01\E\3M_CAC\IPI2K_DBV\raw_file_from_pmcs"
attachments=r"\\acprd01\E\3M_CAC\IPI2K_DBV\mail_attachments"

list_of_files=glob.glob(file_path+"\\"+"*.xls")
#print(list_of_files)
latest_file=max(list_of_files,key=os.path.getctime)

filepath=latest_file
modifiedtime = os.path.getmtime(filepath)
datemodified = datetime.datetime.fromtimestamp(modifiedtime).date()
currentdate=datetime.datetime.today().date()

if str(datemodified)==str(currentdate):
    shutil.copy(latest_file, attachments)
    shutil.copy(latest_file, destination_dir + "/" + "MEP_IPI2K_Result.xls")

    # getting filename
    filename = latest_file[latest_file.index("MEP_IPI2K_Result"):latest_file.index(".xls") + len(".xls")].replace(
        ".xls", "_Verified.xlsx")
    print(filename)
else:
    print("File Not generated by exe")
    print(currentdate,datemodified)

